#pragma once

#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <charconv>
#include <cctype>
#include <cmath>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <functional>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <optional>
#include <ranges>
#include <shared_mutex>
#include <span>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <Windows.h>

#include "NetworkLib/Containers/LockFreeCommon.h"
#include "NetworkLib/Memory/FLockFreeMemoryPool.h"
#include "NetworkLib/Memory/FTlsMemoryPool.h"
#include "NetworkLib/Packet/Buffer/FPacketBuffer.h"
#include "NetworkLib/Packet/Serialization/FPacketReader.h"
#include "NetworkLib/Packet/Serialization/FPacketWriter.h"
#include "RpcLib/Protocol/RpcTypes.h"
#include "RpcLib/Protocol/RpcArgumentSerialization.h"
#include "Generated/Rpc/Cache/CacheRpcMethods.h"
#include "World/WorldCore/WorldTypes.h"
#include "GameData/Common/TGameDataRow.h"
#include "Generated/GameData/Cpp/Common/GameDataEnums.g.h"
#include "Generated/GameData/Cpp/Character/CharacterData.g.h"
#include "Generated/GameData/Cpp/CharacterLevel/CharacterLevelData.g.h"
#include "Generated/GameData/Cpp/Item/ItemData.g.h"
#include "Generated/GameData/Cpp/StatConversion/StatConversionData.g.h"
#include "GameData/Character/FCharacterDataTable.h"
#include "GameData/CharacterLevel/FCharacterLevelDataTable.h"
#include "GameData/Item/FItemDataTable.h"
#include "GameData/StatConversion/FStatConversionTable.h"
#include "World/WorldServer/Domain/FPlayerStatCalculator.h"
