<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ClientNetwork</RootNamespace>
    <AssemblyName>ClientNetwork</AssemblyName>
    <BaseOutputPath>..\..\Out\ClientNetwork\</BaseOutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
