#pragma once

// Network platform
#include <WinSock2.h>
#include <Windows.h>
#include <WS2tcpip.h>
#include <MSWSock.h>

// C++ standard library
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <charconv>
#include <chrono>
#include <concepts>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <optional>
#include <shared_mutex>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <thread>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

// Shared and NetworkLib contracts
#include <format>
#include "Containers/LockFreeCommon.h"
#include "Memory/FLockFreeMemoryPool.h"
#include "Memory/FTlsMemoryPool.h"
#include "Crypto/PacketCipherTypes.h"
#include "Crypto/IPacketCipher.h"
#include "../Foundation/Diagnostics/Tls/FTlsCollectorRuntime.h"
#include "../Foundation/Logging/LoggingTypes.h"
#include "Servers/Core/BackendTypes.h"
#include "Diagnostics/Rio/FRioSendMetricsRuntime.h"
#include "Diagnostics/ServerMonitoringTypes.h"
#include "Servers/Session/ISession.h"
#include "Containers/FLockFreeQueue.h"
#include "Packet/Buffer/FRecvBuffer.h"
#include "Packet/Buffer/FSendSegmentPool.h"
#include "Packet/Framing/PacketTypes.h"
#include "Packet/View/FPacketView.h"
#include "Packet/Framing/IPacketFramer.h"
#include "../Foundation/Logging/ILogger.h"
#include "Diagnostics/FServerMonitoringRuntime.h"
#include "Packet/Framing/ContentHeader.h"
#include "Packet/Buffer/FPacketBuffer.h"
#include "Packet/Serialization/FPacketWriter.h"
#include "Packet/Serialization/FPacketReader.h"
#include "Servers/IServer.h"
#include "Packet/Serialization/FPacketSerialization.h"
#include "Servers/IApplicationHandler.h"
#include "Packet/Buffer/FSendBuffer.h"
#include "Packet/View/FBorrowedViewGuard.h"
