#pragma once

// C++ standard library
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <charconv>
#include <chrono>
#include <cctype>
#include <cmath>
#include <concepts>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <optional>
#include <shared_mutex>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <thread>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

// GameData runtime and generated contracts
#include "Common/TGameDataRow.h"
#include "../../Generated/GameData/Cpp/Common/GameDataEnums.g.h"
#include "../../Generated/GameData/Cpp/Item/ItemData.g.h"
#include "../../Generated/GameData/Cpp/AuctionPolicy/AuctionPolicyData.g.h"
#include "../../Generated/GameData/Cpp/Map/MapData.g.h"
#include "../../Generated/GameData/Cpp/Monster/MonsterData.g.h"
#include "../../Generated/GameData/Cpp/SpawnArea/SpawnAreaData.g.h"
#include "../../Generated/GameData/Cpp/MonsterSpawner/MonsterSpawnerData.g.h"
#include "../../Generated/GameData/Cpp/Character/CharacterData.g.h"
#include "../../Generated/GameData/Cpp/CharacterLevel/CharacterLevelData.g.h"
#include "../../Generated/GameData/Cpp/CombatFormulaPolicy/CombatFormulaPolicyData.g.h"
#include "../../Generated/GameData/Cpp/StatConversion/StatConversionData.g.h"
#include "../../Generated/GameData/Cpp/InventoryPolicy/InventoryPolicyData.g.h"
#include "../../Generated/GameData/Cpp/Currency/CurrencyData.g.h"
#include "../../Generated/GameData/Cpp/MailPolicy/MailPolicyData.g.h"
#include "../../Generated/GameData/Cpp/MailTemplate/MailTemplateData.g.h"
#include "Auction/AuctionPolicyTypes.h"
#include "Character/FCharacterDataTable.h"
#include "CharacterLevel/FCharacterLevelDataTable.h"
#include "Monster/FMonsterDataTable.h"
#include "MonsterSpawner/FMonsterSpawnerDataTable.h"
#include "SpawnArea/FSpawnAreaDataTable.h"
