#pragma once

#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <functional>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <optional>
#include <shared_mutex>
#include <span>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <vector>

#include <Windows.h>
#include "NetworkLib/Containers/LockFreeCommon.h"
#include "NetworkLib/Memory/FLockFreeMemoryPool.h"
#include "NetworkLib/Memory/FTlsMemoryPool.h"
#include "NetworkLib/Packet/Buffer/FPacketBuffer.h"
#include "NetworkLib/Packet/Serialization/FPacketReader.h"
#include "NetworkLib/Packet/Serialization/FPacketWriter.h"
#include "NetworkLib/Packet/View/FPacketView.h"
#include "NetworkLib/Packet/View/FBorrowedViewGuard.h"
#include "NetworkLib/Packet/Framing/ContentHeader.h"
#include "NetworkLib/Packet/Serialization/IContentPacket.h"
#include "NetworkLib/Servers/IServer.h"
#include "NetworkLib/Packet/Serialization/FPacketSerialization.h"

#include "RpcLib/Protocol/RpcTypes.h"
#include "RpcLib/Protocol/RpcMessages.h"
#include "RpcLib/Protocol/RpcArgumentSerialization.h"
#include "RpcLib/Protocol/RpcMessageSerialization.h"
#include "RpcLib/Protocol/RpcWirePacket.h"
#include "RpcLib/Session/FRpcSession.h"
#include "RpcLib/Session/FRpcSessionRegistry.h"
#include "RpcLib/Call/FRpcRequestIdGenerator.h"
#include "RpcLib/Call/FRpcPendingCallManager.h"
#include "RpcLib/Transport/IRpcTransport.h"
#include "RpcLib/Transport/FServerRpcTransport.h"
#include "RpcLib/Client/FOutboundRpcClient.h"
#include "RpcLib/Routing/IRpcContentRouter.h"
#include "RpcLib/Dispatch/FRpcCallContext.h"
#include "RpcLib/Dispatch/TRpcReply.h"
#include "RpcLib/Dispatch/FRpcMethodDispatcher.h"
#include "RpcLib/FRpcCommon.h"
