using System.Text;
using System.Text.Json;

internal sealed record SGeneratedFile(string RelativePath, string Content);

internal static class FGameDataGenerators
{
    public static IReadOnlyList<SGeneratedFile> Generate(
        IReadOnlyList<FGameDataTable> tables,
        IReadOnlyDictionary<string, FGameDataEnumDefinition> enumDefinitions)
    {
        var files = new List<SGeneratedFile>
        {
            new("CSharp/GeneratedGameData.csproj", GenerateCSharpProject()),
            new("Schema/GameDataEnums.schema.yaml", GenerateEnumSchema(enumDefinitions.Values)),
        };
        if (enumDefinitions.Values.Any(definition => definition.IsIncludedOnServer))
        {
            files.Add(new SGeneratedFile(
                "Cpp/Common/GameDataEnums.g.h",
                GenerateCppEnums(enumDefinitions.Values)));
        }
        if (enumDefinitions.Values.Any(definition => definition.IsIncludedOnClient))
        {
            files.Add(new SGeneratedFile(
                "CSharp/Common/GameDataEnums.g.cs",
                GenerateCSharpEnums(enumDefinitions.Values)));
        }

        foreach (FGameDataTable table in tables
            .Where(table => !FGameDataEnumCatalog.IsDefinitionTable(table))
            .OrderBy(table => table.Name, StringComparer.Ordinal))
        {
            files.Add(new SGeneratedFile(
                $"Schema/{table.Name}.schema.yaml",
                GenerateSchema(table)));

            if (table.IsIncludedOnServer)
            {
                files.Add(new SGeneratedFile(
                    $"Data/Server/{table.Name}.yaml",
                    GenerateServerYaml(table)));
                files.Add(new SGeneratedFile(
                    $"Cpp/{table.Name}/{table.Name}Data.g.h",
                    GenerateCppHeader(table, enumDefinitions)));
            }

            if (table.IsIncludedOnClient)
            {
                files.Add(new SGeneratedFile(
                    $"Data/Client/{table.Name}.json",
                    GenerateClientJson(table)));
                files.Add(new SGeneratedFile(
                    $"CSharp/{table.Name}/{table.Name}Data.g.cs",
                    GenerateCSharp(table)));
            }
        }

        return files;
    }

    private static string GenerateEnumSchema(IEnumerable<FGameDataEnumDefinition> definitions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by GameDataGenerator. Do not edit.");
        builder.AppendLine("enums:");
        foreach (FGameDataEnumDefinition definition in definitions.OrderBy(definition => definition.Name, StringComparer.Ordinal))
        {
            builder.AppendLine($"  - name: {FGameDataText.QuoteYaml(definition.Name)}");
            builder.AppendLine($"    target: {definition.Target}");
            builder.AppendLine($"    underlying-type: {FGameDataEnumCatalog.RenderUnderlyingType(definition.UnderlyingType)}");
            builder.AppendLine("    values:");
            foreach (SEnumValue value in definition.Values)
            {
                builder.AppendLine($"      - name: {FGameDataText.QuoteYaml(value.Name)}");
                builder.AppendLine($"        value: {value.NumericValue!.Value}");
            }
        }
        return NormalizeNewLines(builder.ToString());
    }

    private static string GenerateCppEnums(IEnumerable<FGameDataEnumDefinition> definitions)
    {
        FGameDataEnumDefinition[] serverDefinitions = definitions
            .Where(definition => definition.IsIncludedOnServer)
            .OrderBy(definition => definition.Name, StringComparer.Ordinal)
            .ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("#pragma once");
        builder.AppendLine();
        builder.AppendLine("// Generated by GameDataGenerator. Do not edit.");
        builder.AppendLine("namespace GameData::Common");
        builder.AppendLine("{");
        for (int definitionIndex = 0; definitionIndex < serverDefinitions.Length; ++definitionIndex)
        {
            FGameDataEnumDefinition definition = serverDefinitions[definitionIndex];
            builder.AppendLine($"\tenum class E{definition.Name} : {RenderCppEnumUnderlyingType(definition.UnderlyingType)}");
            builder.AppendLine("\t{");
            for (int valueIndex = 0; valueIndex < definition.Values.Count; ++valueIndex)
            {
                SEnumValue value = definition.Values[valueIndex];
                string comma = valueIndex + 1 == definition.Values.Count ? string.Empty : ",";
                builder.AppendLine($"\t\t{value.Name} = {value.NumericValue!.Value}{comma}");
            }
            builder.AppendLine("\t};");
            if (definitionIndex + 1 != serverDefinitions.Length)
            {
                builder.AppendLine();
            }
        }
        builder.AppendLine("}");
        return NormalizeNewLines(builder.ToString());
    }

    private static string GenerateCSharpEnums(IEnumerable<FGameDataEnumDefinition> definitions)
    {
        FGameDataEnumDefinition[] clientDefinitions = definitions
            .Where(definition => definition.IsIncludedOnClient)
            .OrderBy(definition => definition.Name, StringComparer.Ordinal)
            .ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Generated.GameData.Common;");
        builder.AppendLine();
        for (int definitionIndex = 0; definitionIndex < clientDefinitions.Length; ++definitionIndex)
        {
            FGameDataEnumDefinition definition = clientDefinitions[definitionIndex];
            builder.AppendLine($"public enum E{definition.Name} : {RenderCSharpEnumUnderlyingType(definition.UnderlyingType)}");
            builder.AppendLine("{");
            for (int valueIndex = 0; valueIndex < definition.Values.Count; ++valueIndex)
            {
                SEnumValue value = definition.Values[valueIndex];
                string comma = valueIndex + 1 == definition.Values.Count ? string.Empty : ",";
                builder.AppendLine($"    {value.Name} = {value.NumericValue!.Value}{comma}");
            }
            builder.AppendLine("}");
            if (definitionIndex + 1 != clientDefinitions.Length)
            {
                builder.AppendLine();
            }
        }
        return NormalizeNewLines(builder.ToString());
    }

    private static string GenerateSchema(FGameDataTable table)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by GameDataGenerator. Do not edit.");
        builder.AppendLine($"table: {FGameDataText.QuoteYaml(table.Name)}");
        builder.AppendLine($"target: {table.Target}");
        builder.AppendLine($"source: {FGameDataText.QuoteYaml(table.SourceRelativePath)}");
        builder.AppendLine($"primary-key: {FGameDataText.QuoteYaml(table.PrimaryKey!.Name)}");
        builder.AppendLine("fields:");
        foreach (FGameDataField field in table.Fields)
        {
            builder.AppendLine($"  - name: {FGameDataText.QuoteYaml(field.Name)}");
            builder.AppendLine($"    scope: {field.Scope}");
            builder.AppendLine($"    type: {FGameDataText.QuoteYaml(field.Type!.SourceName)}");
            builder.AppendLine($"    primary-key: {field.IsPrimaryKey.ToString().ToLowerInvariant()}");
            builder.AppendLine($"    required: {field.Required.ToString().ToLowerInvariant()}");
            AppendOptionalYamlScalar(builder, "min", field.MinimumText, 4);
            AppendOptionalYamlScalar(builder, "max", field.MaximumText, 4);
            AppendOptionalYamlScalar(builder, "default", field.DefaultText, 4);
            if (field.AllowedValues.Count != 0)
            {
                builder.AppendLine("    allowed:");
                foreach (SEnumValue allowed in field.AllowedValues)
                {
                    builder.AppendLine($"      - name: {FGameDataText.QuoteYaml(allowed.Name)}");
                    if (allowed.NumericValue.HasValue)
                    {
                        builder.AppendLine($"        value: {allowed.NumericValue.Value}");
                    }
                }
            }
            AppendOptionalYamlScalar(builder, "reference", field.Reference, 4);
        }

        return NormalizeNewLines(builder.ToString());
    }

    private static string GenerateServerYaml(FGameDataTable table)
    {
        IReadOnlyList<FGameDataField> fields = table.Fields.Where(field => field.IsIncludedOnServer).ToArray();
        FGameDataField key = table.PrimaryKey!;
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by GameDataGenerator. Do not edit.");
        foreach (FGameDataRow row in table.Rows)
        {
            object keyValue = row.Values[key.Name]!;
            string sectionName = table.Name + FGameDataText.FormatScalar(keyValue, key.Type!);
            builder.AppendLine($"{RenderYamlMappingKey(sectionName)}:");
            foreach (FGameDataField field in fields)
            {
                row.Values.TryGetValue(field.Name, out object? value);
                builder.AppendLine($"  {field.Name}: {RenderYamlValue(value, field.Type!)}");
            }
        }

        return NormalizeNewLines(builder.ToString());
    }

    private static string GenerateClientJson(FGameDataTable table)
    {
        IReadOnlyList<FGameDataField> fields = table.Fields.Where(field => field.IsIncludedOnClient).ToArray();
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
        {
            writer.WriteStartArray();
            foreach (FGameDataRow row in table.Rows)
            {
                writer.WriteStartObject();
                foreach (FGameDataField field in fields)
                {
                    writer.WritePropertyName(field.Name);
                    row.Values.TryGetValue(field.Name, out object? value);
                    WriteJsonValue(writer, value, field.Type!);
                }
                writer.WriteEndObject();
            }
            writer.WriteEndArray();
        }

        return NormalizeNewLines(Encoding.UTF8.GetString(stream.ToArray())) + "\n";
    }

    private static string GenerateCppHeader(
        FGameDataTable table,
        IReadOnlyDictionary<string, FGameDataEnumDefinition> enumDefinitions)
    {
        IReadOnlyList<FGameDataField> fields = table.Fields.Where(field => field.IsIncludedOnServer).ToArray();
        FGameDataField key = table.PrimaryKey!;
        string keyType = RenderCppType(key.Type!);
        string rowName = string.Equals(table.Name, "Item", StringComparison.Ordinal) ? "SItemTemplate" : $"S{table.Name}Data";
        var builder = new StringBuilder();
        builder.AppendLine("#pragma once");
        builder.AppendLine();
        builder.AppendLine("// Generated by GameDataGenerator. Do not edit.");
        FGameDataEnumDefinition[] referencedEnums = fields
            .Where(field => field.Type!.Kind == EGameDataScalarKind.Enum)
            .Select(field => enumDefinitions[field.Type!.EnumName!])
            .DistinctBy(definition => definition.Name, StringComparer.Ordinal)
            .OrderBy(definition => definition.Name, StringComparer.Ordinal)
            .ToArray();
        if (referencedEnums.Length != 0)
        {
            builder.AppendLine("namespace GameData::Common");
            builder.AppendLine("{");
            foreach (FGameDataEnumDefinition definition in referencedEnums)
            {
                builder.AppendLine($"\tenum class E{definition.Name} : {RenderCppEnumUnderlyingType(definition.UnderlyingType)};");
            }
            builder.AppendLine("}");
            builder.AppendLine();
        }
        builder.AppendLine($"namespace GameData::{table.Name}");
        builder.AppendLine("{");

        builder.AppendLine($"\tstruct {rowName} final : GameData::TGameDataRow<{rowName}, {keyType}>");
        builder.AppendLine("\t{");
        builder.AppendLine($"\t\tusing KeyType = {keyType};");
        builder.AppendLine();
        foreach (FGameDataField field in fields)
        {
            string memberName = FGameDataNaming.ToCppMemberName(table.Name, field.Name);
            builder.AppendLine($"\t\t{RenderCppType(field.Type!)} {memberName}{RenderCppInitializer(table, field)};");
        }
        builder.AppendLine();
        string keyMemberName = FGameDataNaming.ToCppMemberName(table.Name, key.Name);
        builder.AppendLine("\t\t[[nodiscard]] constexpr const KeyType& GetKeyValue() const noexcept");
        builder.AppendLine("\t\t{");
        builder.AppendLine($"\t\t\treturn {keyMemberName};");
        builder.AppendLine("\t\t}");
        builder.AppendLine("\t};");
        builder.AppendLine("}");
        return NormalizeNewLines(builder.ToString());
    }

    private static string GenerateCSharp(FGameDataTable table)
    {
        IReadOnlyList<FGameDataField> fields = table.Fields.Where(field => field.IsIncludedOnClient).ToArray();
        FGameDataField key = table.PrimaryKey!;
        string keyType = RenderCSharpType(key.Type!);
        string rowName = string.Equals(table.Name, "Item", StringComparison.Ordinal) ? "ItemData" : $"{table.Name}Data";
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using GameData;");
        if (fields.Any(field => field.Type!.Kind == EGameDataScalarKind.Enum))
        {
            builder.AppendLine("using Generated.GameData.Common;");
        }
        builder.AppendLine();
        builder.AppendLine($"namespace Generated.GameData.{table.Name};");
        builder.AppendLine();

        builder.AppendLine($"public sealed class {rowName} : GameDataRow<{keyType}>");
        builder.AppendLine("{");
        foreach (FGameDataField field in fields)
        {
            string propertyName = FGameDataNaming.ToPascalCase(field.Name);
            string initializer = field.Type!.Kind == EGameDataScalarKind.String ? " = string.Empty;" : string.Empty;
            builder.AppendLine($"    public {RenderCSharpType(field.Type)} {propertyName} {{ get; init; }}{initializer}");
            builder.AppendLine();
        }
        string keyPropertyName = FGameDataNaming.ToPascalCase(key.Name);
        builder.AppendLine($"    public override {keyType} DataId => {keyPropertyName};");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine($"public static class {table.Name}DataTable");
        builder.AppendLine("{");
        builder.AppendLine($"    public static IReadOnlyDictionary<{keyType}, {rowName}> Load(string path) =>");
        builder.AppendLine($"        GameDataTableLoader.Load<{keyType}, {rowName}>(path, ValidateRow);");
        builder.AppendLine();
        builder.AppendLine($"    private static string? ValidateRow({rowName} row)");
        builder.AppendLine("    {");
        if (string.Equals(table.Name, "Item", StringComparison.Ordinal))
        {
            builder.AppendLine("        if (row.ItemDataId == 0)");
            builder.AppendLine("        {");
            builder.AppendLine("            return \"ItemDataId must be greater than zero.\";");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        if (string.IsNullOrWhiteSpace(row.Name))");
            builder.AppendLine("        {");
            builder.AppendLine("            return \"Name must not be empty.\";");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
        foreach (FGameDataField enumField in fields.Where(field => field.Type!.Kind == EGameDataScalarKind.Enum))
        {
            string propertyName = FGameDataNaming.ToPascalCase(enumField.Name);
            builder.AppendLine($"        if (!Enum.IsDefined(row.{propertyName}))");
            builder.AppendLine("        {");
            builder.AppendLine($"            return $\"{propertyName} is not defined: {{row.{propertyName}}}\";");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
        builder.AppendLine("        return null;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return NormalizeNewLines(builder.ToString());
    }

    private static string GenerateCSharpProject()
    {
        return NormalizeNewLines("""
            <Project Sdk="Microsoft.NET.Sdk">

              <PropertyGroup>
                <TargetFramework>net9.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <RootNamespace>Generated.GameData</RootNamespace>
                <AssemblyName>GeneratedGameData</AssemblyName>
                <BaseOutputPath>..\..\..\Out\GeneratedGameData\</BaseOutputPath>
                <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
                <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
              </PropertyGroup>

              <ItemGroup>
                <ProjectReference Include="..\..\..\CSharp\GameData\GameData.csproj" />
                <Compile Include="**\*.g.cs"
                         Exclude="bin\**\*.g.cs;obj\**\*.g.cs" />
              </ItemGroup>

            </Project>
            """) + "\n";
    }

    private static string RenderCppType(FGameDataType type)
    {
        return type.Kind switch
        {
            EGameDataScalarKind.Bool => "bool",
            EGameDataScalarKind.Int32 => "std::int32_t",
            EGameDataScalarKind.UInt32 => "std::uint32_t",
            EGameDataScalarKind.Int64 => "std::int64_t",
            EGameDataScalarKind.UInt64 => "std::uint64_t",
            EGameDataScalarKind.Float => "float",
            EGameDataScalarKind.Double => "double",
            EGameDataScalarKind.String => "std::string",
            EGameDataScalarKind.Enum => $"::GameData::Common::E{type.EnumName}",
            _ => throw new ArgumentOutOfRangeException(nameof(type)),
        };
    }

    private static string RenderCSharpType(FGameDataType type)
    {
        return type.Kind switch
        {
            EGameDataScalarKind.Bool => "bool",
            EGameDataScalarKind.Int32 => "int",
            EGameDataScalarKind.UInt32 => "uint",
            EGameDataScalarKind.Int64 => "long",
            EGameDataScalarKind.UInt64 => "ulong",
            EGameDataScalarKind.Float => "float",
            EGameDataScalarKind.Double => "double",
            EGameDataScalarKind.String => "string",
            EGameDataScalarKind.Enum => $"E{type.EnumName}",
            _ => throw new ArgumentOutOfRangeException(nameof(type)),
        };
    }

    private static string RenderCppInitializer(FGameDataTable table, FGameDataField field)
    {
        if (field.DefaultText != null)
        {
            if (field.Type!.Kind == EGameDataScalarKind.Enum)
            {
                return $" = ::GameData::Common::E{field.Type.EnumName}::{field.DefaultText}";
            }
            if (field.Type.Kind == EGameDataScalarKind.String)
            {
                return $" = {QuoteCppString(field.DefaultText)}";
            }
            if (field.Type.Kind == EGameDataScalarKind.Bool)
            {
                return field.DefaultText.Equals("true", StringComparison.OrdinalIgnoreCase) || field.DefaultText == "1"
                    ? " = true"
                    : " = false";
            }
            return $" = {field.DefaultText}";
        }

        return field.Type!.Kind == EGameDataScalarKind.String ? string.Empty : "{}";
    }

    private static string RenderYamlValue(object? value, FGameDataType type)
    {
        if (value == null)
        {
            return "null";
        }
        if (type.Kind is EGameDataScalarKind.String or EGameDataScalarKind.Enum)
        {
            return FGameDataText.QuoteYaml((string)value);
        }
        return FGameDataText.FormatScalar(value, type);
    }

    private static string RenderYamlMappingKey(string value)
    {
        return value.All(character => char.IsLetterOrDigit(character) || character is '_' or '-')
            ? value
            : FGameDataText.QuoteYaml(value);
    }

    private static void WriteJsonValue(Utf8JsonWriter writer, object? value, FGameDataType type)
    {
        if (value == null)
        {
            writer.WriteNullValue();
            return;
        }

        switch (type.Kind)
        {
            case EGameDataScalarKind.Bool: writer.WriteBooleanValue((bool)value); break;
            case EGameDataScalarKind.Int32: writer.WriteNumberValue((int)value); break;
            case EGameDataScalarKind.UInt32: writer.WriteNumberValue((uint)value); break;
            case EGameDataScalarKind.Int64: writer.WriteNumberValue((long)value); break;
            case EGameDataScalarKind.UInt64: writer.WriteNumberValue((ulong)value); break;
            case EGameDataScalarKind.Float: writer.WriteNumberValue((float)value); break;
            case EGameDataScalarKind.Double: writer.WriteNumberValue((double)value); break;
            case EGameDataScalarKind.String:
            case EGameDataScalarKind.Enum: writer.WriteStringValue((string)value); break;
            default: throw new ArgumentOutOfRangeException(nameof(type));
        }
    }

    private static void AppendOptionalYamlScalar(StringBuilder builder, string name, string? value, int indentation)
    {
        if (value == null)
        {
            return;
        }
        builder.Append(' ', indentation);
        builder.Append(name);
        builder.Append(": ");
        builder.AppendLine(FGameDataText.QuoteYaml(value));
    }

    private static string RenderCppEnumUnderlyingType(EGameDataEnumUnderlyingType underlyingType) => underlyingType switch
    {
        EGameDataEnumUnderlyingType.UInt8 => "std::uint8_t",
        EGameDataEnumUnderlyingType.UInt16 => "std::uint16_t",
        EGameDataEnumUnderlyingType.Int32 => "std::int32_t",
        EGameDataEnumUnderlyingType.UInt32 => "std::uint32_t",
        _ => throw new ArgumentOutOfRangeException(nameof(underlyingType)),
    };

    private static string RenderCSharpEnumUnderlyingType(EGameDataEnumUnderlyingType underlyingType) => underlyingType switch
    {
        EGameDataEnumUnderlyingType.UInt8 => "byte",
        EGameDataEnumUnderlyingType.UInt16 => "ushort",
        EGameDataEnumUnderlyingType.Int32 => "int",
        EGameDataEnumUnderlyingType.UInt32 => "uint",
        _ => throw new ArgumentOutOfRangeException(nameof(underlyingType)),
    };

    private static string QuoteCppString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (char character in value)
        {
            switch (character)
            {
                case '\\': builder.Append("\\\\"); break;
                case '"': builder.Append("\\\""); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case '\0': builder.Append("\\0"); break;
                default: builder.Append(character); break;
            }
        }
        builder.Append('"');
        return builder.ToString();
    }

    private static string NormalizeNewLines(string text) => text.Replace("\r\n", "\n", StringComparison.Ordinal);
}
