#pragma once

// Network platform
#include <WinSock2.h>
#include <Windows.h>
#include <WS2tcpip.h>
#include <MSWSock.h>

// C++ standard library
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <charconv>
#include <chrono>
#include <concepts>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <optional>
#include <shared_mutex>
#include <span>
#include <sstream>
#include <string>
#include <string_view>
#include <thread>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

// Platform and formatting
#include <cstdlib>
#include <stdexcept>
#include <format>

// Shared library contracts
#include "../../Libraries/Connector/MySql/MySqlTypes.h"
#include "../../Libraries/ContentsRuntime/Core/ContentRuntimeTypes.h"
#include "../../Libraries/ContentsRuntime/Core/IContent.h"
#include "../../Libraries/ContentsRuntime/Session/RequestProcessingTypes.h"
#include "../../Libraries/ContentsRuntime/Session/FContentSession.h"
#include "../../Libraries/Foundation/Logging/LoggingTypes.h"
#include "../../Libraries/Foundation/Logging/ILogger.h"
#include "../../Libraries/Foundation/Diagnostics/Timing/TimingTypes.h"
#include "../../Libraries/Foundation/Diagnostics/Tls/FTlsCollectorRuntime.h"
#include "../../Libraries/Foundation/Diagnostics/Timing/FTimingMetricsRuntime.h"
#include "../../Libraries/Foundation/Diagnostics/Timing/FTimingCsvLogger.h"
#include "../../Libraries/Connector/Interfaces/IChatTicketStore.h"
#include "../../Libraries/Connector/Config/RedisChatTicketStoreTypes.h"
#include "../../Libraries/NetworkLib/Packet/Framing/ContentHeader.h"
#include "../../Libraries/NetworkLib/Containers/LockFreeCommon.h"
#include "../../Libraries/NetworkLib/Memory/FLockFreeMemoryPool.h"
#include "../../Libraries/NetworkLib/Memory/FTlsMemoryPool.h"
#include "../../Libraries/NetworkLib/Packet/Buffer/FPacketBuffer.h"
#include "../../Libraries/NetworkLib/Packet/Serialization/FPacketWriter.h"
#include "../../Libraries/NetworkLib/Packet/Serialization/FPacketReader.h"
#include "../../Libraries/NetworkLib/Packet/View/FPacketView.h"
#include "../../Libraries/NetworkLib/Servers/IServer.h"
#include "../../Libraries/NetworkLib/Packet/Serialization/FPacketSerialization.h"
#include "../../Libraries/NetworkLib/Packet/View/FBorrowedViewGuard.h"
#include "../../Libraries/ContentsRuntime/Bridge/IContentBridge.h"
#include "../../Libraries/ContentsRuntime/Threading/FContentThread.h"
#include "../../Libraries/NetworkLib/Crypto/PacketCipherTypes.h"
#include "../../Libraries/NetworkLib/Crypto/IPacketCipher.h"
#include "../../Libraries/NetworkLib/Packet/Serialization/IContentPacket.h"
#include "../../Libraries/GameData/Common/TGameDataRow.h"
#include "../../Generated/GameData/Cpp/Item/ItemData.g.h"
#include "../../Generated/GameData/Cpp/AuctionPolicy/AuctionPolicyData.g.h"
#include "../../Generated/GameData/Cpp/InventoryPolicy/InventoryPolicyData.g.h"
#include "../../Generated/GameData/Cpp/MailPolicy/MailPolicyData.g.h"
#include "../../Libraries/GameData/Auction/AuctionPolicyTypes.h"
#include "../../Libraries/NetworkLib/Packet/Buffer/FRecvBuffer.h"
#include "../../Libraries/NetworkLib/Packet/Framing/PacketTypes.h"
#include "../../Libraries/NetworkLib/Packet/Framing/IPacketFramer.h"
#include "../../Libraries/NetworkLib/Servers/Core/BackendTypes.h"
#include "../../Libraries/Connector/MySql/FMySqlConnection.h"
#include "../../Libraries/Connector/MySql/FMySqlTransaction.h"
#include "../../Libraries/Connector/MySql/FThreadAffinedMySqlCluster.h"
#include "../../Libraries/Connector/MySql/MySqlResultReader.h"
#include "../../Libraries/RpcLib/Protocol/RpcTypes.h"
#include "../../Libraries/RpcLib/Protocol/RpcMessages.h"
#include "../../Libraries/RpcLib/Protocol/RpcArgumentSerialization.h"
#include "../../Libraries/RpcLib/Protocol/RpcMessageSerialization.h"
#include "../../Libraries/RpcLib/Protocol/RpcWirePacket.h"
#include "../../Libraries/RpcLib/Session/FRpcSession.h"
#include "../../Libraries/RpcLib/Session/FRpcSessionRegistry.h"
#include "../../Libraries/RpcLib/Call/FRpcRequestIdGenerator.h"
#include "../../Libraries/RpcLib/Call/FRpcPendingCallManager.h"
#include "../../Libraries/RpcLib/Transport/IRpcTransport.h"
#include "../../Libraries/RpcLib/Dispatch/FRpcCallContext.h"
#include "../../Libraries/RpcLib/Dispatch/TRpcReply.h"
#include "../../Libraries/RpcLib/Dispatch/FRpcMethodDispatcher.h"
#include "../../Libraries/RpcLib/FRpcCommon.h"
#include "../../Libraries/RpcLib/Client/FOutboundRpcClient.h"
#include "../../Generated/Rpc/Cache/CacheRpcMethods.h"

// AuctionHouseServer contracts
#include "Database/AuctionDatabaseTypes.h"
#include "Domain/AuctionResultCode.h"
#include "Domain/AuctionSearchSortType.h"
